spring.application.name=doctor-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_db
spring.datasource.username=postgres
spring.datasource.password=Nikhil@921999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Logging
# ------------------------------------
logging.level.root=INFO
logging.level.com.example.doctorservice=DEBUG

eureka.instance.prefer-ip-address=true