spring.application.name=api-gateway-hms
server.port=9090

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Patient Service
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=patient
spring.cloud.gateway.routes[0].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/patients/**

# Doctor Service
spring.cloud.gateway.routes[1].id=doctor-service
spring.cloud.gateway.routes[1].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/doctors/**

# Appointment Service
spring.cloud.gateway.routes[2].id=appointment-service
spring.cloud.gateway.routes[2].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/appointments/**

# Logging
# ==========================================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO